In [2]:
import numpy as np

In [5]:
np.array([[1,1,1],[1,1,1],[1,1,1]])

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [7]:
mx_1s = np.ones(5)
print(mx_1s)

[1. 1. 1. 1. 1.]


In [9]:
mx_1s.dtype

dtype('float64')

In [13]:
mx_1s = np.ones((3,4))
print(mx_1s)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [15]:
np.ones((3,4), dtype = int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [17]:
mx_0s = np.zeros((3,3))
print(mx_0s)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [18]:
mx_0s = np.zeros((3,3), dtype = bool)
print(mx_0s)

[[False False False]
 [False False False]
 [False False False]]


In [19]:
mx_0s = np.zeros((3,3), dtype = str)
print(mx_0s)

[['' '' '']
 ['' '' '']
 ['' '' '']]


In [20]:
em_str = ''
print(bool(em_str))

False


In [21]:
em_mx = np.empty((3,3))
print(em_mx)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
